//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFOOD.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consecutive
    {
        public int ConsecutiveCode { get; set; }
        public string Description { get; set; }
        public string CurrentConsecutive { get; set; }
        public bool HasPrefix { get; set; }
        public string Prefix { get; set; }
    }
}
