//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFOOD.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int LogID { get; set; }
        public System.DateTime LogDate { get; set; }
        public string ErrCode { get; set; }
        public string Description { get; set; }
    }
}
