//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSCard.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjeta
    {
        public int codTarjeta { get; set; }
        public string portador { get; set; }
        public string numeroTarjeta { get; set; }
        public string tipoTarjeta { get; set; }
        public string marcaTarjeta { get; set; }
        public System.DateTime fechaExpiracion { get; set; }
        public string cvv { get; set; }
        public Nullable<decimal> saldo_disponible { get; set; }
        public Nullable<decimal> limite_credito { get; set; }
        public string codUsuario { get; set; }
    }
}
