//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFood_ECommerce.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentToCustomer
    {
        public int CartID { get; set; }
        public int CustomerID { get; set; }
        public bool Status { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
