//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFood_ECommerce.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceTypeToProduct
    {
        public string PriceTypeCode { get; set; }
        public string ProductCode { get; set; }
        public double Price { get; set; }
    
        public virtual PriceType PriceType { get; set; }
        public virtual Product Product { get; set; }
    }
}
